context:
  version: "2.0.0"

package:
  name: q-kx-arrow
  version: ${{ version }}

source:
  path: ..
  filter:
    exclude:
      - recipe/**

build:
  number: 0

requirements:
  build:
    - ${{ compiler("cxx") }}
    - cmake
    - make
  host:
    - libarrow
    - libparquet
  run:
    - libarrow
    - libparquet

tests:
  - script:
    - if: unix
      then:
        - test -f ${PREFIX}/lib/q/mod/kx/arrow/init.q
    - if: linux and x86_64
      then:
        - test -f ${PREFIX}/lib/q/mod/kx/arrow/clib.li64.so
    - if: linux and aarch64
      then:
        - test -f ${PREFIX}/lib/q/mod/kx/arrow/clib.la64.so
    - if: osx and arm64
      then:
        - test -f ${PREFIX}/lib/q/mod/kx/arrow/clib.ma64.so
    - if: osx and x86_64
      then:
        - test -f ${PREFIX}/lib/q/mod/kx/arrow/clib.mi64.so
    - if: win
      then:
        - if not exist %PREFIX%\\lib\\q\\mod\\kx\\arrow\\init.q exit 1
        - if not exist %PREFIX%\\lib\\q\\mod\\kx\\\arrow\\clib.wi64.dll exit 1
