jobs:
  include:
  - dist: bionic
    os: linux
  - dist: focal
    os: linux    
  - osx_image: xcode12.5
    os: osx
  - os: windows
language: c
compiler: gcc
os: linux
dist: xenial

before_install:
  - export FILE_ROOT="arrowkdb"
  - export BUILD="True"
  - export TESTS="True"

  # Run instructions to install or build Arrow libray
  - if [[ $BUILD == "True" ]]; then
      chmod +x travis_setup.sh; 
      ./travis_setup.sh;
      export LIB="cmake/$FILE_ROOT/lib";
      mkdir cmake;
    else
      export LIB="";
    fi
    
  # Set ARROW_INSTALL to the Arrow installation directory
  - if [[ $BUILD == "True" ]]; then
      if [[ $TRAVIS_OS_NAME == "windows" || $TRAVIS_OS_NAME == "osx" ]]; then
        export ARROW_INSTALL=$TRAVIS_BUILD_DIR/cbuild/install;
        export LD_LIBRARY_PATH=$ARROW_INSTALL/lib:$LD_LIBRARY_PATH;
        export DYLD_LIBRARY_PATH=$ARROW_INSTALL/lib:$LD_LIBRARY_PATH;
        export PATH=$ARROW_INSTALL/bin:$PATH;
      fi
    fi
    
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      QLIBDIR=l64; OD=$L64;
    elif [[ $TRAVIS_OS_NAME == "osx" ]]; then
      QLIBDIR=m64; OD=$M64;
    elif [[ $TRAVIS_OS_NAME == "windows" ]]; then
      QLIBDIR=w64; OD=$W64;
    else
      echo "unknown OS ('$TRAVIS_OS_NAME')" >&2; exit 1;
    fi

  - export QLIBDIR
  - mkdir qhome;
  - export QHOME=$(pwd)/qhome;
  - export PATH=$QHOME/$QLIBDIR:$PATH;
  
  # Set up q for testing and execute tests on multiple 
  - if [[ $TESTS == "True" && "x$OD" != "x" && "x$QLIC_KC" != "x" ]]; then
      curl -u $NEXUS_USER:$NEXUS_PASS -o qhome/q.zip -L $OD;
      unzip -d qhome qhome/q.zip;
      rm qhome/q.zip;
      echo -n $QLIC_KC |base64 --decode > qhome/kc.lic;
    else
      echo No kdb+, no tests;
    fi

  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      export FILE_TAIL="zip";
    else
      export FILE_TAIL="tgz";
    fi
  - export FILE_NAME=$FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.$FILE_TAIL

  # Make binaries for the library as appropriate
  - if [[ $BUILD == "True" && $TRAVIS_OS_NAME == "windows" ]]; then
      cd cmake && cmake -G "Visual Studio 15 2017 Win64" .. -DARROW_INSTALL=$ARROW_INSTALL;
      cmake --build . --config Release;
      cmake --build . --config Release --target install;
      cd ..;
    elif [[ $BUILD == "True" && ( $TRAVIS_OS_NAME == "linux" || $TRAVIS_OS_NAME == "osx" ) ]]; then
      cd cmake && cmake .. -DCMAKE_BUILD_TYPE=Release -DARROW_INSTALL=$ARROW_INSTALL && make install && cd .. ;
    fi

script:
  - if [[ $TESTS == "True" && "x$OD" != "x" && "x$QLIC_KC" != "x" ]]; then
      curl -o test.q -L https://github.com/KxSystems/hdf5/raw/master/test.q;
      if [[ $TRAVIS_OS_NAME == "windows" ]]; then
        q test.q tests -q && q test.q tests/null_mapping -q && q test.q tests/null_bitmap -q;
      else
        q test.q tests -q && q test.q tests/null_mapping -q && q test.q tests/null_bitmap -q && q test.q tests/orc_dataloader -q;
      fi
    fi
  - if [[ $TRAVIS_OS_NAME == "windows" && $BUILD == "True" ]]; then
      7z a -tzip -r $FILE_NAME ./cmake/$FILE_ROOT/*;
    elif [[ $BUILD == "True" && ( $TRAVIS_OS_NAME == "linux" || $TRAVIS_OS_NAME == "osx" ) ]]; then  
      tar  -zcvf $FILE_NAME -C cmake/$FILE_ROOT .;
    elif [[ $TRAVIS_OS_NAME == "windows" ]]; then
      7z a -tzip $FILE_NAME README.md install.bat LICENSE q docs examples proto;
    elif [[ $TRAVIS_OS_NAME == "linux" || $TRAVIS_OS_NAME == "osx" ]]; then
      tar  -zcvf $FILE_NAME README.md install.sh LICENSE q docs examples proto;
    fi

deploy:
  provider: releases
  token: "$GITHUB_APIKEY"
  file: "$FILE_NAME"
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = windows || $TRAVIS_OS_NAME = osx || ($TRAVIS_DIST = bionic && $TRAVIS_OS_NAME = linux) 
  skip_cleanup: 'true'
  
